# Student Service - QA Environment (Docker)
env: qa

server:
  port: "8080"

database:
  host: postgres
  port: "5432"
  user: postgres
  password: postgres
  name: university

project_service:
  url: http://project_api:8081
  grpc: project_api:9090

kafka:
  brokers:
    - kafka:9092
  topic: student-messages
